# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'auth' do
  pod 'GoogleSignIn', '~> 4.1'
end
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for auth

  # target 'auth-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'authTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'auth-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for auth-tvOS

  target 'auth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
